FROM ubuntu:24.04

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y samba

WORKDIR /root

COPY smb.conf entry.sh ./

CMD ["/bin/bash", "/root/entry.sh"]

# create users
