networks:
  default6:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd3a:138e:8fd0:0001::/64
services:
  website:
    restart: always
    build: website/.
    entrypoint: ["/bin/sh", "/root/entry.sh"]
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default6
    volumes:
      - ./website/letsencrypt:/etc/letsencrypt
  gitea:
    restart: always
    image: gitea/gitea:latest-rootless
    ports:
      - "2222:2222"
    networks:
      - default6
    volumes:
      - ./website/gitea/data:/var/lib/gitea
      - ./website/gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  monerod:
    restart: always
    build: monerod/.
    entrypoint: ["/bin/sh", "/home/ubuntu/entry.sh"]
    stdin_open: true
    tty: true
    ports:
      - "18080:18080"
      - "18081:18081"
    networks:
      - default6
    volumes:
      - ./monerod/.bitmonero:/home/ubuntu/.bitmonero
  p2pool:
    stop_grace_period: 1m # TODO reduce m_shutdownCountdown to reduce this
    restart: always
    build: p2pool/.
    entrypoint: ["/bin/sh", "/home/ubuntu/entry.sh"]
    stdin_open: true
    tty: true
    ports:
      - "3333:3333"
      - "37888:37888"
      - "37889:37889"
    networks:
      - default6
    volumes:
      - ./p2pool/cache:/home/ubuntu/cache
      - /dev/hugepages:/dev/hugepages
  minecraft:
    restart: always
    build: minecraft/.
    entrypoint: ["/bin/sh", "/home/ubuntu/entry.sh"]
    ports:
      - "25565:25565"
    networks:
      - default6
    volumes:
      - ./minecraft/world:/home/ubuntu/world
  minecraft_bedrock:
    restart: always
    build: minecraft_bedrock/.
    entrypoint: ["/bin/sh", "/home/ubuntu/entry.sh"]
    ports:
      - "19132:19132/udp"
      - "19133:19133/udp"
    networks:
      - default6
    volumes:
      - ./minecraft_bedrock/worlds:/home/ubuntu/worlds
  # terraria:
  #   restart: always
  #   build: terraria/.
  #   entrypoint: ["/bin/sh", "/home/ubuntu/entry.sh"]
  #   ports:
  #     - "7777:7777"
  #   networks:
  #     - default6
  #   volumes:
  #     - ./terraria/worlds:/home/ubuntu/worlds
