services:
  website:
    restart: always
    build: website/.
    # entrypoint: ["/bin/sh", "/home/matt/entry.sh"]
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   - ./monerod/.bitmonero:/home/matt/.bitmonero
  monerod:
    restart: always
    build: monerod/.
    entrypoint: ["/bin/sh", "/home/matt/entry.sh"]
    ports:
      - "18080:18080"
    volumes:
      - ./monerod/.bitmonero:/home/matt/.bitmonero
  p2pool:
    restart: always
    build: p2pool/.
    entrypoint: ["/bin/sh", "/home/matt/entry.sh"]
    ports:
      - "3333:3333"
      - "37888:37888"
      - "37889:37889"
    volumes:
      - ./p2pool/cache:/home/matt/cache
      - /dev/hugepages:/dev/hugepages
  minecraft:
    restart: always
    build: minecraft/.
    entrypoint: ["/bin/sh", "/home/matt/entry.sh"]
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft/world:/home/matt/world
  terraria:
    restart: always
    build: terraria/.
    entrypoint: ["/bin/sh", "/home/matt/entry.sh"]
    ports:
      - "7777:7777"
    volumes:
      - ./terraria/worlds:/home/matt/worlds
